import { EmbeddingService } from './EmbeddingService';
import { logger } from '../core/logger';

/**
 * DALC Result Schema
 * traces: ADR-005, Blueprint §7
 */
export interface DALCResult {
  similarity: number;
  status: 'PASS' | 'COLLAPSE_DETECTED' | 'COLLAPSE_UNRESOLVED' | 'PREDICTED_COLLAPSE_AVOIDED';
  regenerationAttempts: number;
  finalOutput: string;
}

/**
 * Diversity-Aware Latent Consensus (DALC) Service
 * traces: FR-04, FR-05, SM-7, ADR-005, PRD §7.1
 * Enforces output diversity between Proposer and Router Plan.
 */
export class DALC {
  public static readonly COLLAPSE_THRESHOLD = 0.85; // ADR-005: MUST be ≤ 0.85
  private static readonly MAX_REGENERATIONS = 2; // FR-05

  /**
   * Orthogonality directive for re-generation
   * traces: FR-05 verbatim
   */
  public static readonly ORTHOGONALITY_DIRECTIVE = 
    'Your prior response was semantically identical to the routing plan. Provide a structurally distinct solution exploring an alternative approach.';

  /**
   * Predict if a synthesis will likely collapse based on expert embeddings
   * @param expertEmbeddings Array of embeddings from initial expert responses
   * @param planEmbedding Embedding of the routing plan
   */
  public static predictCollapse(expertEmbeddings: number[][], planEmbedding: number[]): boolean {
    if (expertEmbeddings.length === 0) return false;
    
    // Calculate centroid of experts
    const dim = expertEmbeddings[0].length;
    const centroid = new Array(dim).fill(0);
    for (const emb of expertEmbeddings) {
      for (let i = 0; i < dim; i++) {
        centroid[i] += emb[i] / expertEmbeddings.length;
      }
    }
    
    const similarity = EmbeddingService.cosineSimilarity(centroid, planEmbedding);
    logger.debug({ predictedSimilarity: similarity.toFixed(4) }, '[DALC] Predicted collapse check');
    return similarity >= this.COLLAPSE_THRESHOLD;
  }

  /**
   * Enforce diversity check and handle re-generation
   * @param proposerOutput Initial output from the proposer
   * @param routerPlan The routing plan generated by the Router
   * @param callProposer Callback to re-invoke the proposer with a directive
   * @param planEmbedding Optional pre-calculated plan embedding
   */
  public static async enforce(
    proposerOutput: string,
    routerPlan: string,
    callProposer: (directive: string) => Promise<string>,
    planEmbedding?: number[]
  ): Promise<DALCResult> {
    const embeddingService = EmbeddingService.getInstance();
    let currentOutput = proposerOutput;
    let attempts = 0;

    const actualPlanEmbedding = planEmbedding || await embeddingService.embed(routerPlan);

    while (attempts <= this.MAX_REGENERATIONS) {
      const outputEmbedding = await embeddingService.embed(currentOutput);
      const similarity = EmbeddingService.cosineSimilarity(actualPlanEmbedding, outputEmbedding);

      if (similarity < this.COLLAPSE_THRESHOLD) {
        return {
          similarity,
          status: attempts === 0 ? 'PASS' : 'COLLAPSE_DETECTED',
          regenerationAttempts: attempts,
          finalOutput: currentOutput,
        };
      }

      attempts++;
      if (attempts <= this.MAX_REGENERATIONS) {
        logger.info({ similarity: similarity.toFixed(4), attempt: attempts }, '[DALC] Collapse detected. Retrying with orthogonality directive...');
        currentOutput = await callProposer(this.ORTHOGONALITY_DIRECTIVE);
      } else {
        logger.warn({ similarity: similarity.toFixed(4), max_attempts: this.MAX_REGENERATIONS }, '[DALC] Collapse UNRESOLVED');
        return {
          similarity,
          status: 'COLLAPSE_UNRESOLVED',
          regenerationAttempts: this.MAX_REGENERATIONS,
          finalOutput: currentOutput,
        };
      }
    }

    return {
      similarity: 1.0,
      status: 'COLLAPSE_UNRESOLVED',
      regenerationAttempts: attempts,
      finalOutput: currentOutput,
    };
  }
}
