import { EmbeddingService } from './EmbeddingService';

/**
 * DALC Result Schema
 * traces: ADR-005, Blueprint §7
 */
export interface DALCResult {
  similarity: number;
  status: 'PASS' | 'COLLAPSE_DETECTED' | 'COLLAPSE_UNRESOLVED';
  regenerationAttempts: number;
  finalOutput: string;
}

/**
 * Diversity-Aware Latent Consensus (DALC) Service
 * traces: FR-04, FR-05, ADR-005, PRD §7.1
 * Enforces output diversity between Proposer and Router Plan.
 */
export class DALC {
  private static readonly COLLAPSE_THRESHOLD = 0.85; // ADR-005: MUST be ≤ 0.85
  private static readonly MAX_REGENERATIONS = 2; // FR-05

  /**
   * Orthogonality directive for re-generation
   * traces: FR-05 verbatim
   */
  public static readonly ORTHOGONALITY_DIRECTIVE = 
    'Your prior response was semantically identical to the routing plan. Provide a structurally distinct solution exploring an alternative approach.';

  /**
   * Enforce diversity check and handle re-generation
   * @param proposerOutput Initial output from the proposer
   * @param routerPlan The routing plan generated by the Router
   * @param callProposer Callback to re-invoke the proposer with a directive
   */
  public static async enforce(
    proposerOutput: string,
    routerPlan: string,
    callProposer: (directive: string) => Promise<string>
  ): Promise<DALCResult> {
    const embeddingService = EmbeddingService.getInstance();
    let currentOutput = proposerOutput;
    let attempts = 0;

    const planEmbedding = await embeddingService.embed(routerPlan);

    while (attempts <= this.MAX_REGENERATIONS) {
      const outputEmbedding = await embeddingService.embed(currentOutput);
      const similarity = EmbeddingService.cosineSimilarity(planEmbedding, outputEmbedding);

      if (similarity < this.COLLAPSE_THRESHOLD) {
        return {
          similarity,
          status: attempts === 0 ? 'PASS' : 'COLLAPSE_DETECTED',
          regenerationAttempts: attempts,
          finalOutput: currentOutput,
        };
      }

      attempts++;
      if (attempts <= this.MAX_REGENERATIONS) {
        console.log(`[DALC] Collapse detected (sim=${similarity.toFixed(4)}). Retrying attempt ${attempts}...`);
        currentOutput = await callProposer(this.ORTHOGONALITY_DIRECTIVE);
      } else {
        console.warn(`[DALC] Collapse UNRESOLVED after ${this.MAX_REGENERATIONS} attempts (sim=${similarity.toFixed(4)}).`);
        return {
          similarity,
          status: 'COLLAPSE_UNRESOLVED',
          regenerationAttempts: this.MAX_REGENERATIONS,
          finalOutput: currentOutput,
        };
      }
    }

    // Should not reach here
    return {
      similarity: 1.0,
      status: 'COLLAPSE_UNRESOLVED',
      regenerationAttempts: attempts,
      finalOutput: currentOutput,
    };
  }
}
